/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SqliteIndexRouteImport } from './routes/sqlite/index'
import { Route as PostgresIndexRouteImport } from './routes/postgres/index'
import { Route as MysqlIndexRouteImport } from './routes/mysql/index'
import { Route as SqliteIdRouteImport } from './routes/sqlite/$id'
import { Route as PostgresIdRouteImport } from './routes/postgres/$id'
import { Route as MysqlIdRouteImport } from './routes/mysql/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqliteIndexRoute = SqliteIndexRouteImport.update({
  id: '/sqlite/',
  path: '/sqlite/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostgresIndexRoute = PostgresIndexRouteImport.update({
  id: '/postgres/',
  path: '/postgres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MysqlIndexRoute = MysqlIndexRouteImport.update({
  id: '/mysql/',
  path: '/mysql/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqliteIdRoute = SqliteIdRouteImport.update({
  id: '/sqlite/$id',
  path: '/sqlite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostgresIdRoute = PostgresIdRouteImport.update({
  id: '/postgres/$id',
  path: '/postgres/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MysqlIdRoute = MysqlIdRouteImport.update({
  id: '/mysql/$id',
  path: '/mysql/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mysql/$id': typeof MysqlIdRoute
  '/postgres/$id': typeof PostgresIdRoute
  '/sqlite/$id': typeof SqliteIdRoute
  '/mysql/': typeof MysqlIndexRoute
  '/postgres/': typeof PostgresIndexRoute
  '/sqlite/': typeof SqliteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mysql/$id': typeof MysqlIdRoute
  '/postgres/$id': typeof PostgresIdRoute
  '/sqlite/$id': typeof SqliteIdRoute
  '/mysql': typeof MysqlIndexRoute
  '/postgres': typeof PostgresIndexRoute
  '/sqlite': typeof SqliteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mysql/$id': typeof MysqlIdRoute
  '/postgres/$id': typeof PostgresIdRoute
  '/sqlite/$id': typeof SqliteIdRoute
  '/mysql/': typeof MysqlIndexRoute
  '/postgres/': typeof PostgresIndexRoute
  '/sqlite/': typeof SqliteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mysql/$id'
    | '/postgres/$id'
    | '/sqlite/$id'
    | '/mysql/'
    | '/postgres/'
    | '/sqlite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mysql/$id'
    | '/postgres/$id'
    | '/sqlite/$id'
    | '/mysql'
    | '/postgres'
    | '/sqlite'
  id:
    | '__root__'
    | '/'
    | '/mysql/$id'
    | '/postgres/$id'
    | '/sqlite/$id'
    | '/mysql/'
    | '/postgres/'
    | '/sqlite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MysqlIdRoute: typeof MysqlIdRoute
  PostgresIdRoute: typeof PostgresIdRoute
  SqliteIdRoute: typeof SqliteIdRoute
  MysqlIndexRoute: typeof MysqlIndexRoute
  PostgresIndexRoute: typeof PostgresIndexRoute
  SqliteIndexRoute: typeof SqliteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqlite/': {
      id: '/sqlite/'
      path: '/sqlite'
      fullPath: '/sqlite/'
      preLoaderRoute: typeof SqliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postgres/': {
      id: '/postgres/'
      path: '/postgres'
      fullPath: '/postgres/'
      preLoaderRoute: typeof PostgresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysql/': {
      id: '/mysql/'
      path: '/mysql'
      fullPath: '/mysql/'
      preLoaderRoute: typeof MysqlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqlite/$id': {
      id: '/sqlite/$id'
      path: '/sqlite/$id'
      fullPath: '/sqlite/$id'
      preLoaderRoute: typeof SqliteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postgres/$id': {
      id: '/postgres/$id'
      path: '/postgres/$id'
      fullPath: '/postgres/$id'
      preLoaderRoute: typeof PostgresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysql/$id': {
      id: '/mysql/$id'
      path: '/mysql/$id'
      fullPath: '/mysql/$id'
      preLoaderRoute: typeof MysqlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MysqlIdRoute: MysqlIdRoute,
  PostgresIdRoute: PostgresIdRoute,
  SqliteIdRoute: SqliteIdRoute,
  MysqlIndexRoute: MysqlIndexRoute,
  PostgresIndexRoute: PostgresIndexRoute,
  SqliteIndexRoute: SqliteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
